### ISSUE TITLE
Falto agregar una imagen de preferencia COOLTEXT.com

### ISSUE THREAD

**Issue by IoTeacher** [Osvaldo-Baltazar/Osvaldo-Baltazar#1]
Una vez que las corrija lo solicitado tendrá el:

![](https://images-na.ssl-images-amazon.com/images/I/41mUvRO4kXL.jpg)

**Comment by Osvaldo-Baltazar** [comment]
![image](https://user-images.githubusercontent.com/55269095/109266691-3a906d00-77bd-11eb-82d0-d8d53d7ac46f.png)
